services:
  - type: web
    name: globapay-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://globapay-backend.vercel.app/

databases:
  - name: globapay-db
    plan: free
    databaseName: globapay
    user: globapay_user
